

namespace PhishExplorer
{
    static class SiteList
    {
        public static List<string> GetTrustedSites()
        {
            return new List<string>
            {
                "Google.fr",
                "Orange.fr",
                "Ask.com",
                "Twitter.com",
                "Linkedin.com",
                "Free.fr",
                "Lemonde.fr",
                "Lefigaro.fr",
                "Ebay.fr",
                "Commentcamarche.net",
                "Lequipe.fr",
                "Google.com",
                "T.co",
                "Allocine.fr",
                "Cdiscount.com",
                "Wordpress.com",
                "Jeuxvideo.com",
                "Nouvelobs.com",
                "Meteofrance.com",
                "Pagesjaunes.fr",
                "Tumblr.com",
                "Facebook.com",
                "Dailymotion.com",
                "Adcash.com",
                "Sfr.fr",
                "Viadeo.com",
                "Programme-tv.net",
                "Instagram.com",
                "Linternaute.com",
                "Ovh.com",
                "Pinterest.com",
                "Youtube.com",
                "Msn.com",
                "Voyages-sncf.com",
                "Over-blog.com",
                "Stackoverflow.com",
                "Ad6media.fr",
                "Paypal.com",
                "Priceminister.com",
                "Societe.com",
                "20minutes.fr",
                "Apple.com",
                "Wikipedia.org",
                "Pole-emploi.fr",
                "Leparisien.fr",
                "Fnac.com",
                "Lexpress.fr",
                "Bing.com",
                "Tf1.fr",
                "Microsoft.com",
                "Deezer.com",
                "T411.me",
                "Yahoo.com",
                "Booking.com",
                "Journaldunet.com",
                "Reverso.net",
                "Credit-agricole.fr",
                "Outbrain.com",
                "Boursorama.com",
                "Amazon.com",
                "Labanquepostale.fr",
                "Leboncoin.fr",
                "Vente-privee.com",
                "Seloger.com",
                "Ovh.net",
                "Imgur.com",
                "Akamaihd.net",
                "Colissimo.fr",
                "Wordpress.org",
                "Bfmtv.com",
                "Clubic.com",
                "Amazon.fr",
                "Tripadvisor.fr",
                "Laposte.net",
                "Wordreference.com",
                "Rueducommerce.fr",
                "Liberation.fr",
                "Cpasbien.pe",
                "01net.com",
                "Lepoint.fr",
                "Doctissimo.fr",
                "Zone-telechargement.com",
                "Live.com",
                "Huffingtonpost.fr",
                "Adxcore.com",
                "Aufeminin.com",
                "Googleusercontent.com",
                "Aliexpress.com",
                "Lesechos.fr",
                "Bnpparibas.net",
                "Vimeo.com",
                "Prestashop.com",
                "Openclassrooms.com"
            };
        }
        public static List<string> GetKnowPhishingSites()
        {
            return new List<string>
            {

            };
        }
    }
}
